language: go

go:
- "1.15" 			
env:
- GO111MODULE=on

install: 
- go mod download
script:
- go build
- go test -coverprofile=coverage.txt -covermode=atomic 
#- go test -coverprofile=coverage.txt -covermode=atomic -v

#Codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
