language: go

go:
- "1.15" 			
env:
- GO111MODULE=on
services: mongodb

install: 
# DESCOMENTAR SI SE USA TASK 
- snap install task --classic
- go mod download
script:
- task aux
- go build
- go run ./main/main.go
- go test -coverprofile=coverage.txt -covermode=atomic 
#- go test -coverprofile=coverage.txt -covermode=atomic -v

#Codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
