version: '3'

tasks:
  aux:
    cmds:
     - echo 'Holaaaaaaa'
  install_dep:
    summary: |
      Install dependencies
    cmds:
      - go mod download
      
  test:
    summary: |
      Execute tests
    cmds: 
      #- go test -coverprofile=coverage.txt -covermode=atomic -v
      - go test -v
      
  docker_local:
    summary: |
      Execute local
    cmds: 
      #- go test -coverprofile=coverage.txt -covermode=atomic -v
      - docker run --rm -t -v `pwd`:/app/test pedromfc/evaluaugr
      
  docker_travis:
    summary: |
      Execute docker in travis
    cmds: 
      - docker run -t -v $TRAVIS_BUILD_DIR:/app/test pedromfc/evaluaugr
      
  build:
    summary: |
      build project
    cmds: 
      - go build
      
  codecov:
    summary: |
      send to codecov
    cmds: 
      - bash <(curl -s https://codecov.io/bash)
