version: '3'

tasks:
  aux:
    cmds:
     - echo 'Holaaaaaaa'
  install_dep:
    summary: |
      Install dependencies
    cmds:
      - go mod download
      
  test:
    summary: |
      Execute tests
    cmds: 
      - go test -coverprofile=coverage.txt -covermode=atomic -v
      
  build:
    summary: |
      build project
    cmds: 
      - go build
      
  codecov:
    summary: |
      send to codecov
    cmds: 
      - bash <(curl -s https://codecov.io/bash)
