# https://github.com/marketplace/actions/docker-build-tag-push

name: Subir a github packages
on: 
  push:
    paths:
      - 'Dockerfile'
jobs:
  my-job:
    name: My Job 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: prueba
          registry: ghcr.io/github
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }} 

      #- uses: mr-smithers-excellent/docker-build-push@v3
      #  with:
      #    image: pedromfc/prueba
      #    registry: docker.io
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}