name: Subir a github packages
on: push
jobs:
  my-job:
    name: My Job 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pedromfc/evaluaugr
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }} 