# https://github.com/marketplace/actions/docker-build-tag-push

name: Subir a github packages
on: 
  push:
    paths:
      - 'Dockerfile'
jobs:
  my-job:
    name: My Job 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code

      - name: log
        run: |
          echo ${{ secrets.DOCKER_TOKEN}} | docker login ghcr.io -u PedroMFC --password-stdin
          docker build --tag ghcr.io/github/prueba/test:$GITHUB_SHA .
          docker push ghcr.io/github/prueba/test:$GITHUB_SHA

      #- uses: mr-smithers-excellent/docker-build-push@v3
      #  with:
      #    image: pedromfc/prueba
      #    registry: docker.io
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}